更新部分高数相关答案
NJUPTFreeExams/NJUPT-General-Free-Exams pull request #77
Opened 2024-12-11 11:04 UTC by sunaqr

2024-12-15 09:23 UTC, BlockLune commented
感谢您的贡献！请等待我们的 Review 通过，就会合并啦！再次感谢！

2024-12-16 04:50 UTC, toulzx requested changes

2024-12-16 04:50 UTC, toulzx commented on public/高等数学A（下）/高数下同步练习册答案2019.pdf
和这个 [同步练习册答案[2020-2021-2].doc](https://github.com/NJUPTFreeExams/NJUPT-General-Free-Exams/blob/master/public/%E9%AB%98%E7%AD%89%E6%95%B0%E5%AD%A6A%EF%BC%88%E4%B8%8B%EF%BC%89/%E5%90%8C%E6%AD%A5%E7%BB%83%E4%B9%A0%E5%86%8C%E7%AD%94%E6%A1%88%5B2020-2021-2%5D.doc) 是同样的内容。
此 pdf 额外包含了第 6 章内容，经检查 commit 记录，这在之前是`高数（上）`部分的内容。

这两个文件具体创建时间应该可追溯至 201402。

2024-12-16 04:50 UTC, toulzx commented on public/高等数学A（上）/练习册答案/高数上-对齐.pdf
与此文件 [[2017]练习册答案.pdf](https://github.com/NJUPTFreeExams/NJUPT-General-Free-Exams/blob/master/public/%E9%AB%98%E7%AD%89%E6%95%B0%E5%AD%A6A%EF%BC%88%E4%B8%8A%EF%BC%89/%E7%BB%83%E4%B9%A0%E5%86%8C%E7%AD%94%E6%A1%88/%5B2017%5D%E7%BB%83%E4%B9%A0%E5%86%8C%E7%AD%94%E6%A1%88.pdf) 重复。

2024-12-16 04:50 UTC, toulzx commented on public/线性代数与解析几何/线代答案2023（部分）/1.1.jpg
建议移动文件夹至 [/线性代数与解析几何/练习册/](https://github.com/NJUPTFreeExams/NJUPT-General-Free-Exams/tree/master/public/%E7%BA%BF%E6%80%A7%E4%BB%A3%E6%95%B0%E4%B8%8E%E8%A7%A3%E6%9E%90%E5%87%A0%E4%BD%95/%E7%BB%83%E4%B9%A0%E5%86%8C) 中。

2024-12-16 05:29 UTC, toulzx commented
我做了一些修改，不过因为没有权限被拒了 TT
![image](https://github.com/user-attachments/assets/60f78b6f-0c9d-4636-9547-2d731417d880)

2024-12-16 05:44 UTC, BlockLune commented
> 我做了一些修改，不过因为没有权限被拒了 TT ![image](https://private-user-images.githubusercontent.com/57480529/395970550-60f78b6f-0c9d-4636-9547-2d731417d880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMjgxMjQsIm5iZiI6MTczNDMyNzgyNCwicGF0aCI6Ii81NzQ4MDUyOS8zOTU5NzA1NTAtNjBmNzhiNmYtMGM5ZC00NjM2LTk1NDctMmQ3MzE0MTdkODgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA1NDM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYTA2NmMzZDViMzE0OGMzZTUxNzVkOTZhYzYzYWFkNTY3MmE4YWFiOGJmOWM5MDljNmI1ZDA2M2JmMDU1ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._DvJ4vahLk4Qu8A3jTIfx1Sw7vvLtSCuA8H0RLs0OBA)

@toulzx 要用下面这条命令推送：

```bash
git push git@github.com:sunaqr/NJUPT-General-Free-Exams.git HEAD:master
```

2024-12-16 06:49 UTC, toulzx commented
> > 我做了一些修改，不过因为没有权限被拒了 TT ![image]()
> 
> @toulzx 要用下面这条命令推送：
> 
> ```shell
> git push git@github.com:sunaqr/NJUPT-General-Free-Exams.git HEAD:master
> ```
> 
> 我用这条命令是可以推送上来的。

还是不行，不知道是不是 Codespaces 的缘故 QAQ
我从这边直接给 @sunaqr 的仓库 [pr](https://github.com/sunaqr/NJUPT-General-Free-Exams/pull/1) 了，等他合并吧。

2024-12-18 02:34 UTC, closed without merging