更新线代、高数、体育理论考试
NJUPTFreeExams/NJUPT-General-Free-Exams pull request #78
Opened 2024-12-18 02:59 UTC by sunaqr

新增线代练习册答案2023（部分）
新增高数上练习册答案（版本较老仅做整合）
新增高数下练习册答案（版本较老仅做搬运）
体育理论考试新题库（多个资料供参考，实际题库可能不止资料涉及范畴）

2024-12-18 03:01 UTC, sunaqr commented
？怎还是提不了PR

2024-12-18 11:24 UTC, BlockLune commented
@sunaqr 请问为什么把 #77 关了呢？这个是做了什么更改呀... 😂

2024-12-18 11:25 UTC, BlockLune commented
@toulzx 您之前在 #77 是做了什么更改提交不了来着，我在这个 PR 改

2024-12-18 11:53 UTC, sunaqr commented
> @sunaqr 请问为什么把 #77 关了呢？这个是做了什么更改呀... 😂

呃呃，不太会用GitHub或者git的操作，也没太听懂，以为是中间有个commit出现问题，就重新fork了一个最新的，在上面重新进行新增，现在也还是不太懂问题在哪（）

2024-12-18 12:00 UTC, sunaqr commented
抱歉抱歉，我刚刚重新看了一遍才明白了发生了什么，好像让你们多辛苦了，抱歉抱歉，对GitHub和git不是很熟悉

2024-12-18 12:02 UTC, BlockLune commented
没事没事，我来修改吧

2024-12-18 13:23 UTC, toulzx commented
> @toulzx 您之前在 #77 是做了什么更改提交不了来着，我在这个 PR 改

等我今晚再试试这次修改可不可行。

2024-12-18 16:16 UTC, toulzx requested changes
参考 review comment 进行修改后合并。

2024-12-18 16:16 UTC, toulzx commented on public/高等数学A（下）/《高等数学》同步练习册（下）答案2019.1doc.pdf
与 #77 中上传的 [PDF](https://github.com/sunaqr/NJUPT-General-Free-Exams/blob/b5e10fd639d56de016555e6fa0bf67bbf2064475/public/%E9%AB%98%E7%AD%89%E6%95%B0%E5%AD%A6A%EF%BC%88%E4%B8%8B%EF%BC%89/%E9%AB%98%E6%95%B0%E4%B8%8B%E5%90%8C%E6%AD%A5%E7%BB%83%E4%B9%A0%E5%86%8C%E7%AD%94%E6%A1%882019.pdf) 重复，

TODO: 
- 替换为该无水印版本，并重命名为 `同步练习册答案_201402__2019高数下.pdf`；
- 重命名 [同步练习册答案[2020-2021-2].doc](https://github.com/NJUPTFreeExams/NJUPT-General-Free-Exams/blob/master/public/%E9%AB%98%E7%AD%89%E6%95%B0%E5%AD%A6A%EF%BC%88%E4%B8%8B%EF%BC%89/%E5%90%8C%E6%AD%A5%E7%BB%83%E4%B9%A0%E5%86%8C%E7%AD%94%E6%A1%88%5B2020-2021-2%5D.doc)  为 `同步练习册答案_201402.doc`。

2024-12-18 16:16 UTC, toulzx commented on public/线性代数与解析几何/练习册/线代答案2023（部分）/1.1.jpg
@sunaqr 请问线代练习册答案扫描的是你自己的作业吗？如果是的话我们需要加个说明（TODO: 文件夹重命名）。

2024-12-18 16:16 UTC, toulzx commented on public/体育理论考试/24-25学年第一学期 教师版 选择题库.docx
本次上传的确认为一个版本的题库，且与仓库已有的 PDF 内容一致。
TODO: 保留一套 `.docx` 文件，删除仓库中 PDFs。重命名为 `教师版_判断题库_231204` 和 `教师版_选择题库_231204`

2024-12-18 16:20 UTC, sunaqr commented on public/线性代数与解析几何/练习册/线代答案2023（部分）/1.1.jpg
并不是自己的作业，该图片来自老师分享

2024-12-18 16:36 UTC, toulzx commented
@sunaqr 

我这边无法直接修改你的提交，烦请处理你仓库里的 PR: https://github.com/sunaqr/NJUPT-General-Free-Exams/pull/1

当你合并后此 PR 应该会自动更新。

不要再删掉仓库啦 X)

2024-12-18 16:43 UTC, toulzx commented on public/线性代数与解析几何/练习册/线代答案2023（部分）/1.1.jpg
> 并不是自己的作业，该图片来自老师分享

好的～

2024-12-19 07:52 UTC, toulzx requested changes

2024-12-19 07:52 UTC, toulzx commented on package-lock.json
@BlockLune pakage-lock.json 文件是本地自动生成的，这个目前需要远程仓库同步吗？

2024-12-19 07:59 UTC, BlockLune commented on package-lock.json
Lockfile 应该会比 package.json 中更明确地标识出使用的包版本信息，应该留着吧。

2024-12-19 08:00 UTC, BlockLune commented on package-lock.json
问了下 AI，也说是建议留着：
<img width="995" alt="image" src="https://github.com/user-attachments/assets/64eaad15-c612-4349-b9fd-c13716c81583" />

2024-12-19 08:01 UTC, toulzx commented on package-lock.json
> 问了下 AI，也说是建议留着： <img alt="image" width="995" src="https://private-user-images.githubusercontent.com/39331194/397276825-64eaad15-c612-4349-b9fd-c13716c81583.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1OTU1MjMsIm5iZiI6MTczNDU5NTIyMywicGF0aCI6Ii8zOTMzMTE5NC8zOTcyNzY4MjUtNjRlYWFkMTUtYzYxMi00MzQ5LWI5ZmQtYzEzNzE2YzgxNTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDA4MDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5OTg4YTM0ODExZTcwYWQ5N2RjOGRmNTM1ZDA0MTMyNTkwNzk0ZDU0NDgyODhhNDBhN2QyYmU3NjU1YTQ5MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jSzFpxlWiE2LNf8ZrkqzfHPDgOOj2h3mLdOFQQS5nKM">

哈哈哈，好的~
那应该差不多了，可以准备合并了。

2024-12-19 08:09 UTC, BlockLune approved these changes

2024-12-19 08:12 UTC, toulzx approved these changes

2024-12-19 11:04 UTC, merged